#!/usr/bin/python3
"""defining a class square"""


class Square:
    """class square defined"""
    def __init__(self, size=0):
        """defined the initialization for class square"""
        self.__size = size

    @property
    def area(self):
        """return area of square"""
        return self.__area

    @property
    def size(self):
        """Getter method to retrieve self"""
        return self.__size

    @size.setter
    def size(self, value):
        """setter method to set size"""
        if type(value) != int:
            raise TypeError("size must be an integer")
        if value < 0:
            raise ValueError("size must be >= 0")
        self.__size = value
        self.__area = value ** 2
